version: "3.9"

services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}"
    env_file: .env
    environment:
      - "DATABASE_URL=postgres://postgres:postgres@db:5432/postgres"
      - "REDIS_CHANNEL_LAYER_HOST=redis"
    depends_on:
      - redis
      - db
#    depends_on:
#      redis:
#        condition: service_healthy
#      db:
#        condition: service_healthy

  redis:
    image: redis:7
    expose:
      - "6379"
    ports:
      - "6379"
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  db:
    image: postgres:15
    user: postgres
    volumes:
      - dj_chan_postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    expose:
      - "5432"
    ports:
      - "5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  adminer:
    image: adminer
    ports:
      - "8123:8080"

volumes:
  dj_chan_postgres_data:
